---
title: "Project-plan"
output: pdf_document
bibliography: bibliography.bib
csl: vancouver.csl
fontsize: 11pt
---
<!-- If you need more text you can always expand on trauma as a global health issue, 
trauma in Sweden (see SweTraus annual report), trauma quality improvement programs 
and so on. -->
<!--Sånt jag ev kan lägga til
problem med få pat per sjukhus. viktigt med register. alla pat sen 2011 registreras. 
dödsorsaksanalys och tid till reg i traumaregistret.-->
Abbreviations
=====
* AIS - Abbreviated Injury Scale
* ATLS - Advanced Trauma Life Support
* LMIC - Low and middle income countries
* M&M - Morbidity and Mortality Conferences
* NISS - New Injury Severity Score 
* OFI - Opportunity for improvement
* PTC - Primary Trauma Care
* SweTrau - The Swedish trauma registry


Background
=====

Trauma, defined as the clinical entity composed of physical injury and the body's associated response.[@Gerdin] It is one of the leading causes of mortality and morbidity in the world, representing about 9 % of annual global deaths. Among people under the age of 45 trauma is the most common cause of death. Over the last decade almost 50 million people worldwide have died from trauma.[@GBD_2017_Causes_of_Death_Collaborators2018-oe].

Not only does trauma represent a large share of the global mortality rate, but studies 
have also shown a significant difference in outcome depending on where patients are
treated. It has for example been shown that trauma patients in Sweden who were 
treated at a trauma center rather than a non-trauma center have a 41 % lower 
30-day adjusted mortality rate. [@Candefjord2022-pe] 

Some studies indicate that the number of trauma-related deaths that potentially could have been prevented are as high as 20 to over 50 %. [@Drake2020-kx; @Ray2016-jo; @Ghorbani2018-dh] Preventable deaths varies not only between trauma centers and non-trauma centers. There is a significant difference between high income counties and low and middle income countries (LMICs). It is estimated that 2 million lives could be saved annually if LMICs and high income countries had equal fatality numbers for severe injuries.[@Mock2012-lx]  <!-- Korrekt, det om LMICs är bra och kan vara med ffa i KI:s uppsats. Om du vill publicera får det inte plats -->


Advanced Trauma Life Support and Primary Trauma Care
------------
Several different systems are being used in Trauma care. 
Such as Advanced Trauma Life Support (ATLS) and Primary Trauma Care (PTC), 
where ATLS is the more established system. The purpose of these systems is to 
secure a time-efficient, standardized and structured way of treating trauma 
patients.[@FACS; @Kadhum2020-wa]

ATLS is practiced in over 80 countries and 1 million doctors have gone thru 
this training.[@FACS] 

PTC is also used in over 80 countries, however more 
frequently in low and middle-income countries. One reason for this could be that 
the PTC program is free while ATLS is not.[@Kadhum2020-wa]

 New Injury Severity Score 
------------
<!-- See my comment above on the association between distance to the aim and relavance for the aim. This is not relevant to the aim and should therefore be farther away from it. I'm not sure it's relevant at all, at least not as a separate section. SVAR: TÄnkte att man kunde ha med det iom att vi ändå använder oss av oss av NISS och AIS i metoden? Men hade bara tänkt ha det i KI-uppsatsen.-->
The NISS is an anatomic severity scale developed to assess multiple-injured patients. The NISS score a patient get is based on the Abbreviated Injury Scale (AIS) points from the injured body regions. The higher NISS score the more serious injury the patients suffers from.[@Li2021-ag]

NISS takes injuries in 6 different body regions into account. Those are head/neck, face, chest, abdomen, extremiteis and external. The NISS is the sum of the squares of the highest AIS codes in these regions, meaning that all three injuries can be in the same region or in separate regions. AIS can vary from 1-5, and the NISS from 1-75.[@Li2021-ag]


Morbidity and Mortality Conferences
------------
An important part of trauma care evaluation and improvement is Mortality and Morbidity Conferences (M&M). This is a multidisciplinary conference with representatives from all medical specialties and professions in the trauma team. The purpose of M&M is to learn from the care provided, identify opportunities for improvements, and implement corrective actions.[@Aboumatar2007-ws] As it is not possible to analyze every trauma case in detail audit filters are often used to decide which cases that are to be reviewed at M&M. Such audit filter can be time frames in which a test should be taken or a specific treatment provided.[@Evans2009-oy]. <!-- Feel free to provide more specific examples of audit filters. Audit filters and their association to M&M could also be a separate section. SVAR: Uppfattade på Jonatan som att jag skulle hålla det så generellt som möjligt i intro. Jag ger exempel på audit filters och kopplingen till M&M i metoden. Men jag kan göraett stycke om det här om ni tycker det passar bättre. -->

Trauma Registries
------------
<!--När du pratar specifikt om dessa trauma registry som vi faktist använder så hör det hemma i metoden. Så stycken nedan kan flyttas/slås ihop. SVAR: ELIAS SKRIVER OM SVENSKA TRAUMAREGISTRET OCH TCQD UNDER INTRO, MEN ÄNDRADE OM NU. TYCKER DU ATT DETTA FUNKAR BÄTTRE? TYCKER ATT INTRO BLIR GANSAKA KORT MEN KAN FÖRSÖKA SKRIVA OM ANNAT FÖR UTFYLLNAD. -->



Oppotrunity for improvement
------------
<!--Även detta hör hemma i metoden. Titta på Elias och Husseins arbeten. SVAR: Bättre såhär? -->
Whether there is opportunity for improvement for a specific case or not is decided during M&M where selected trauma casees are reviewed. Opportunity for improvement (OFI) is defined as when the trauma care for a patient does not match the best practice guidelines in at least one aspect.[@Sanddal2011-cl]

OFI can be a more nuanced measure for trauma care improvement than the more established terms preventable deaths and non preventable deaths. This is because there can be OFI in a case where a patient has died, even if the death was not preventable.[@Traumaguidelines09] Furthermore there is no consensus for classification of preventable and non preventable death, leading authors to use different classifications.[@Montmany2016-hz]. The term OFI also has the advantage over the term preventable death by sounding more positive and encouraging, preventing review board members from having to classify colleagues patient care as inappropriate.[@Sanddal2011-cl]

Trauma subgroups
------------
Since trauma patients is a heterogeneous group, it is important to have a 
sufficient understanding of OFIs for different trauma subgroups.[@Coats2020-wj]. Some examples of subgroups are men and women, blunt and penetrating trauma, geriatric, major and minor trauma and Traumatic brain injury.[@arsrapportswetrau]

In Sweden almost two thirds of trauma patients are men and just over 60% are in the age between 18-64. For example, traumatic injuries from stabbing and from shooting violence are more common in men while women are over represented in fall traumas. There is a lot of existing data about subgroups regarding transportation time to hospital, NISS score at the Emergency department, rehabilitation, morbidity and mortality rate and so on. [@arsrapportswetrau]

Knowledge gap 
------------

Despite having all this data about the trauma patients it is poorly understood whether different subgroups have greater opportunities for improvement (OFI) than others. The most common cause of death after injury is hemorrhage. Among these patients, problem in decision making, technical skills and making decisions between surgery and radiology were some of the areas were OFIs were found.[@OReilly2013] However we do not know whether the same OFI areas apply for the trauma subgroups, or in what frequency. 
<!-- You haven't mentioned subgroups before, so you might want to introduce these in a separate section first. SVAR: Som stycket ovan?-->


Aim
------------
In this study we aim to assess the frequency of opportunity for improvement in the following important clinical subgroups: men and women, blunt and penetrating injuries, minor and major trauma, and across body regions injured. 


<!-- Aim bör vara i slutet på introduktionen. 
Tänkt att introduktionen ska vara som en stor tratt, börjar brett och så sakta smalnas det av så att du förklarat varför just ditt aim är av värde. Från Varför trauma är dåligt -> Massa mellansteg -> varför vi behöver titta på ofi i olika grupper -->



Methods
=====

<!--Stora delar av det du skriver ovan hör fortfarande hemma i metoddelen. Se Elias och Husseins arbeten -->

Study design
------------
This is a registry based cohort study that uses data from two different Swedish
trauma registries. 

The first registry is the Trauma registry at the Karolinska University Hospital 
in Solna, which includes about 21000 patients between the years 2012 and 2021. 

The second registry is the the trauma Quality Database which is a subset of the trauma registry and includes about 2200 patients selected for review between 2014 and 2021. The trauma care quality database includes details and conclusions from the M&M.

We will link these databases using... <!-- Use first person active voice, much easier to read --> By linking these databases together the opportunity for improvement in the trauma 
subgroups mentioned in the introduction will be assessed.

<!-- Present key elements of study design -->

Setting
-------
The Karolinska University Hospital in Solna, Stockholm, is the leading trauma center in Sweden, and ranked as one of the best hospitals in the world<!-- Provide a source, if you want to include this: SVAR, första och andra meningen har samma källa, är det fel hänvisat då?-->. The hospital is a level 1 trauma center.[@Karolinska] The Trauma department at the Karolinska University Hospital in Solna handles about 1800 trauma cases every year, out of which about 200 are children. KUH <!--Aldrig förkortningen KUH? Sett att de andra studenterna använt det. -->is the primary trauma center for a population of 2,8 million people.[@Traumanks] 

In Sweden there is a national trauma registry (SweTrau) holding records of trauma cases from 48 out of 49 hospitals who recieves major trauma. To meet the inclusions criterias for SweTrau you must be over 15 years of age, been exposed to a traumatic event leading to trauma team activation, or have a NISS over 15 without trauma team activation. Or patients moved to a hospital within 7 days of a traumatic event with NISS over 15. [@swetrau]

Trauma patients are divided into priority one and two by the paramedics using certain criteria, such as trauma mechanism, GCS points and blood pressure. To Karolinska Solna only those who are classified as a priority one by the pre hospital professionals are admitted. [@Granstrom2012]

A trauma priority one is considered directly life threatening. Therefore when arriving to Karolinska Solna every patient is taken care of by a full trauma team. This team consists of a trauma leader who is a general surgeon or a resident in general surgery and an anesthetist with a nurse specialized in anesthesiology. The team also has an orthopedic surgeon, radiologist, radiology nurse, emergency medicine nurse, surgical nurse and assistant nurses.[@Granstrom2012]

At KUH all trauma patients are included in the KUH trauma registry. The KUH trauma registry is a part of the Swedish Trauma Registry, with the same eligibility criteria. Audit filters then identify certain trauma cases for whom the care might have deviated from the gold standard treatment based on different criteria. Such criteria are GCS 8 or less but the patient was not intubated, time to CT longer than 20 minutes, time to Surgery and so on. Then a manual selection is done by a nurse, during which some cases are removed from the group of potential OFI cases because obvious reasons for the deviation can be found. The patients who are then left are discussed at a M&M where doctors and nurses from several specialties participate. At this conference every case is reviewed. When OFI is found in a case, that specific OFI is described in the trauma quality database. Then it is recoded as "Yes, at least one OFI identified" or "No, no OFIs identified"





<!-- Describe the setting, locations, and relevant dates, including
periods of recruitment, exposure, follow-up, and data collection -->

Participants
------------

All patients from KUH trauma registry and from the Trauma Quality Database.


<!-- Cohort study: Give the eligibility criteria, and the sources and
methods of selection of participants. Describe methods of
follow-up. For matched studies, give matching criteria and number of
exposed and unexposed -->

<!-- Case-control study: Give the eligibility criteria, and the
sources and + methods of case ascertainment and control
selection. Give the rationale for the choice of cases and
controls. For matched studies, give matching criteria and the number
of controls per case -->

<!-- Cross-sectional study: Give the eligibility criteria, and the
sources and methods of selection of participants -->

Variables and data sources/measurements
---------------------------------------
The data from the trauma registries were analyzed for OFI in seperate cohorts. The cohorts were: men and women, blunt and penetrating injuries, minor and major trauma ,and across body regions injured. Gender and age will be continuous variables. The location of injuries will be analyzed based on AIS codes and AIS scores will be used to gruop patients into fitting cohorts. 
<!-- Vet inte om jag fattat detta rätt, men jag ska alltså använda AIS-scores för att dela in patienter i de olika cohorterna, då för att avgöra om de uppnår tillräcklig allvarlighetsgrad för att räknas som major trauma? Sen Titta på specifika koder för vilka kroppsdelar som drabbats? Blir det då olika underkategorier som ex en kategori för trubbigt trauma mot buken och en med skarpt trauma mot buken. Eller blir det att jag tittar på OFI för truppigt och skarpt trauma som helhet och sen de olika kroppsdelarna oavsett om det är skarpt eller trubbigt? (Detta är bara lösa tankar som vi kan diskutera när vi ses, har lite svårt att visualisera detta, men det kommer nog klarna när jag väl börjar arbeta med datan. ) -->OFI  was treated as a binary variable, with "yes" and "no" as the only possible outcome. For the M&M conference to put a "yes" in the OFI section at at least one of the following areas needed to differ from the best practice  guidelines for trauma care: emergency department triage; tertiary survey; processing; communication; time to computed tomography; time to surgical intervention; level of physician and nursing competency; level of care; neurosurgical intervention; hospital staff routine; resource management; logistics and technology; overall management and documentation.<!-- This information should be included in the section above instead SVAR: såhär?-->


Göra en tablell här för inklusion och exklusionskriterier för de olika cohorterna baserat på på AIS scores. 

Se elias och hussein

<!--Egentligen är det första gången du tydligt definerar vad OFI är. Du ska även definera de andra variablerna, kön/ålder/penetrerande osv osv. Lär på vad "major traum" är samt hur AIS scores fungerar för att extrahera kroppsdelar -->



<!-- Clearly define all outcomes, exposures, predictors, potential
confounders, and effect modifiers. Give diagnostic criteria, if
applicable. For each variable of interest, give sources of data and
details of methods of assessment (measurement). Describe comparability
of assessment methods if there is more than one group -->

Bias 
----
To prevent research bias all data will be scrambled while used to write the analysis model.



<!-- Describe any efforts to address potential sources of bias -->

Study size 
----------


<!-- Explain how the study size was arrived at -->


<!-- Explain how quantitative variables were handled in the
analyses. If applicable, describe which groupings were chosen and why
-->

Statistical methods
-------------------
The stastistical computing program R will be used to analyze the data.
<!-- 

(a) Describe all statistical methods, including those used to control
for confounding

(b) Describe any methods used to examine subgroups and interactions

(c) Explain how missing data were addressed 

(d) 

Cohort study: If applicable, explain how loss to follow-up was addressed 

Case-control study:If applicable, explain how matching of cases and
controls was addressed

Cross-sectional study: If applicable, describe analytical methods
taking account of sampling strategy

(e) Describe any sensitivity analyses
-->
Ethical considerations
=====

All patients have given consent before added to Swetrau and Trauma Quality Database. As this is a registry based study no interventions were made that could effect the patients. The only risk with this typ of studies is that personal information could leak. In these registries however, all personal data was scrambled to minimize that risk. 

Ethical permission has been granted for tis project. Dnr number for this permission is 2021-02541 and 2021-0253.

DET STÅR ATT ALLA GETT MEDGIVANDE FÖR ATT LÄGGAS TILL I SWETRAU PÅ DERAS HEMSIDA. MEN HUR FUNKAR DET MED DE SOM DOG INNAN SAMTYCKE GAVS? Jonatan pratade om att man antog samtycke för de patienterna. Men hittar ingen info om detta. 
<!--Jag skulle bara undvika att nämna det exakt. Vi kan prata om det med Martin senare men det är 100% ok att använda datan -->

En skriftlig redogörelse av projektets utveckling
=====

All data är redan insamlad från start och finns tillgängliga i de registry som beskrivs i projektredogörelsen. Datan kommer delas in efter olika trauma-subgrupper. De variabler som kommer användas är "Ja" där det finns "Opportunity for improvement" samt "nej" där det inte finns "opportunity for improvement.

Hittills har jag
- Läst in mig på ämnet
- Skrivit Introduktion
- Påbörjat materiela och metod
- Börjat sätta mig in i R som är det program som kommer användas för att sammanställa data.

• Hur data planeras presenteras (t ex tabeller och hur de kan struktureras, diagramtyper, 
vävnadssnitt, intervjucitat etc) 

Datan kommer presenteras i en tabell där de aktuella subgrupperna kommer presenteras samt huruvuda det finns OFI för dessa grupper. Det kommer även redogöras för i vilken utsträckning varje subgrupp har OFI. 

• Hur data planeras analyseras; vilka statistiska metoder för jämförelser mellan en eller 
flera grupper, andra matematiska metoder, kvalitativ analys etc --> Detta skulle jag behöva diskutera med er innan jag kan svara.


Ingen reservplan behövs då all data finns insamlad och risken för att projektet inte går att genomföra somplanerat bedöms minimal.

References
=====
